app:
  site: "localhost"
  devMode: true
  mode: "self"
  secret: "codex-compiler-1x1"
  migrationsPath: "migrations"
  managment:
    username: "admin"
    password: "admin1234"

database:
  driver: "postgres"
  host: "database"
  port: "5432"
  managment:
    username: "postgres"
    password: "1234"
  dbname: "mydatabase"
  sslmode: "disable"
  timezone: "UTC"

redis:
  driver: "redis"
  port: "6379"
  managment:
    username: "redis"
    password: "secret"

http:
  host: "localhost"
  port: "8080"
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s
  allowedOrigins:
    - "http://localhost"
    - "http://localhost:8080"
    - "http://127.0.0.1:8080"
  allowedMethods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowedHeaders:
    - "Accept"
    - "Accept-Encoding"
    - "Authorization"
    - "Content-Length"
    - "Content-Type"
    - "X-CSRF-Token"
    - "X-Requested-With"
    - "Origin"
  exposedHeaders:
    - "Content-Length"
    - "Content-Type"
  allowCredentials: true
  proxyHeader: "X-Forwarded-For"
